# LISTA 5 - EXPRESIONES REGULARES - regex101.com
## <ins>Ejercicios Obligatorios </ins>

In [2]:
import re

## EJERCICIO 1

In [15]:
text = """En un lugar de la Mancha, de cuyo nombre no quiero acordarme, 
no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, 
adarga antigua, rocín flaco y galgo corredor"""
tokens = re.split(r"\W+", text) # W es cualquier caracter que sea una letra, + es todo el espacio despues del item anterior hasta el siguiente
print(tokens)

['En', 'un', 'lugar', 'de', 'la', 'Mancha', 'de', 'cuyo', 'nombre', 'no', 'quiero', 'acordarme', 'no', 'ha', 'mucho', 'tiempo', 'que', 'vivía', 'un', 'hidalgo', 'de', 'los', 'de', 'lanza', 'en', 'astillero', 'adarga', 'antigua', 'rocín', 'flaco', 'y', 'galgo', 'corredor']


El siguiente texto contiene una secuencia de palabras delimitadas por espacios y caracteres de puntuación (puntos y comas). Elabora una expresión regular a partir de la cual podamos descomponer (método split) el texto en todas las palabras que lo componen:

Alternativamente, TAMBIÉN puedes buscar (método findall) todas las palabras existentes en el texto.
```
TEXTO = """En un lugar de la Mancha, de cuyo nombre no quiero acordarme, 
no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, 
adarga antigua, rocín flaco y galgo corredor"""
```

## EJERCICIO 2

In [16]:
text = """En 1492 los Reyes Católicos financiaron el proyecto del navegante Cristóbal 
Colón en la búsqueda de una nueva ruta comercial con Asia a través del océano 
Atlántico, y proclamarían la expulsión de los judíos. La llegada al Nuevo Mundo 
y la posterior conquista de América forjaron la creación del Imperio español. 
Durante los siguientes siglos España se alzaría como actor principal del mundo 
occidental y primera potencia de la época. Durante los siglos xvi y xvii 
tendría lugar también la época de mayor apogeo de la cultura y las artes 
hispanas conocida como Siglo de Oro.

El Imperio español en 1580, tras la unificación de la península ibérica bajo un 
único rey español Felipe II, comprendía América del Sur, América Central y el 
Caribe, grandes áreas de América del Norte en diferentes grados de influencia o 
control, las islas Filipinas en Asia, así como enclaves de diversa importancia 
en las costas de África y la India. Incluía además numerosas posesiones en 
Europa, los Países Bajos españoles, el Ducado de Milán o el Reino de Nápoles, la 
mayoría de ellas perdidas tras la paz de Utrecht de 1713."""

tokens = re.findall(r'\d{4}',text)
print(tokens)

['1492', '1580', '1713']


Escribe una expresión regular que capture los años del siguiente texto acerca de la historia de España obtenido de la Wikipedia:
```
TEXTO = """En 1492 los Reyes Católicos financiaron el proyecto del navegante Cristóbal 
Colón en la búsqueda de una nueva ruta comercial con Asia a través del océano 
Atlántico, y proclamarían la expulsión de los judíos. La llegada al Nuevo Mundo 
y la posterior conquista de América forjaron la creación del Imperio español. 
Durante los siguientes siglos España se alzaría como actor principal del mundo 
occidental y primera potencia de la época. Durante los siglos xvi y xvii 
tendría lugar también la época de mayor apogeo de la cultura y las artes 
hispanas conocida como Siglo de Oro.

El Imperio español en 1580, tras la unificación de la península ibérica bajo un 
único rey español Felipe II, comprendía América del Sur, América Central y el 
Caribe, grandes áreas de América del Norte en diferentes grados de influencia o 
control, las islas Filipinas en Asia, así como enclaves de diversa importancia 
en las costas de África y la India. Incluía además numerosas posesiones en 
Europa, los Países Bajos españoles, el Ducado de Milán o el Reino de Nápoles, la 
mayoría de ellas perdidas tras la paz de Utrecht de 1713."""
```

## EJERCICIO 3

Escribe una expresión regular que detecte caracteres simbólicos (\W) repetidos y los sustituya por una única ocurrencia:

PISTA: puedes referenciar a un grupo previamente capturado mediante \\{número}.
```
TEXTO = "¡¡¡¡¡¡¡QUÉ SORPRESA!!!!!!!"
```

In [ ]:
print(re.sub(r"(\W)\1+", r"\1","¡¡¡¡¡¡¡QUÉ SORPRESA!!!!!!!"))

¡QUÉ SORPRESA!


## EJERCICIO 4

In [3]:
import re
print(re.sub(r"(\b\w+\b )\1+", r"\1","Me lo he pasado muy muy muy bien.")) # Importante añadir el espacio en blanco

Me lo he pasado muy bien.


Escribe una expresión regular que detecte palabras repetidas y las reemplace por una única ocurrencia: 

PISTA: metacaracteres \w y \b.
```
TEXTO = "Me lo he pasado muy muy muy bien."
```

## EJERCICIO 5

In [15]:
import re

TEXTO = """Se ha facturado un total de 1500 € al usuario test@dominio.es durante 
el año 2019. Otros usuarios, como prueba@otro.com con 123.32€ o new@contact.com han gastado 
solamente 500€."""

p = r'(?P<email>\w+@\w+\.\w+)|(?P<precio>\d+(.\d+)?\s?€)'

res = re.finditer(p, TEXTO)

emails = []
precios = []

for match in res:
    if match.group('email'):
        emails.append(match.group('email')) # Hay que volver a indicarle que es un email o devuelve un objeto
    if match.group('precio'):
        precios.append(match.group('precio'))

print(f"Emails: {emails}")
print(f"Precios: {precios}")


Emails: ['test@dominio.es', 'prueba@otro.com', 'new@contact.com']
Precios: ['1500 €', '123.32€', '500€']


Escribe una expresión regular que extraiga las direcciones de correo electrónico y los importes del siguiente texto. Asigna al grupo que contenga el email el nombre correo y al que contenga el importe precio:
```
TEXTO = """Se ha facturado un total de 1500 € al usuario test@dominio.es durante 
el año 2019. Otros usuarios, como prueba@otro.com o new@contact.com han gastado 
solamente 500€."""
```


## EJERCICIO 6

In [24]:
TELEFONOS = "968 12 23 31, 900 141 142, 945112233, 656-247733"
p = r"\b(\d{3} \d{2} \d{2} \d{2}|\d{3} \d{3} \d{3}|\d{9}|\d{3}-\d{6})\b"
res = re.finditer(p, TELEFONOS)

l = []
for match in res:
    x = (match.group()).replace(" ","") # Limpio el token en dos pasos
    x = x.replace("-","")
    l.append(x)

print(l)

['968122331', '900141142', '945112233', '656247733']


Dada la siguiente enumeración de números de teléfono con diferentes formatos, prepara una expresión regular que sea capaz de reconocerlos y de devolverlos con el mismo formato:
```
TELEFONOS = "968 12 23 31, 900 141 142, 945112233, 656-247733"
```

## EJERCICIO 7

In [30]:
def isEmail(str):
    p =r"[a-zA-Z0-9.-_]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,6}"
    return re.search(p,str) is not None

print(isEmail("alberto_45@gmail.com"))
print(isEmail("#€@gmail.com"))

True
False



Validación de direcciones de correo electrónico. Escribe una expresión regular que valide si una dirección de correo electrónico es correcta según el formato estándar. El formato debe ser nombre@dominio.ext, donde:

<ul>
    <li>nombre puede contener letras, números, puntos, guiones bajos y guiones.</li>
    <li>dominio puede contener letras y números.</li>
    <li>ext debe ser de 2 a 6 letras (por ejemplo, .com, .es, .info).</li>
</ul>